language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  # A token generated on GitHub allowing Travis to push code on you repository.
  # Set in the Travis settings page of your repository, as a secure variable.
  github_token: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB32Ue+TVi6ibuD1XJzaTheRYbfUPj4hUvfJJ+QgsiRm <comment>
  keep_history: true
  on:
    branch: master